# Generated by Django 2.2 on 2019-04-23 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Promocod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=15)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=999, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('type_room', models.CharField(max_length=100)),
                ('count_person', models.IntegerField()),
                ('cost_per_night', models.DecimalField(decimal_places=3, max_digits=19)),
                ('description', models.CharField(max_length=500)),
                ('arrival_dates', models.ManyToManyField(blank=True, related_name='arrival_dates', to='mainapp.Data')),
                ('depature_dates', models.ManyToManyField(blank=True, related_name='depature_dates', to='mainapp.Data')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_booking', models.IntegerField(unique=True)),
                ('arrival_date', models.DateField()),
                ('depature_date', models.DateField()),
                ('number_room', models.IntegerField()),
                ('type_room', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('promocode', models.CharField(blank=True, max_length=15)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Visitor')),
            ],
        ),
    ]
