# Generated by Django 2.2 on 2019-05-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type_of_drink', models.CharField(choices=[('1', 'non-alcoholic'), ('2', 'beer'), ('3', 'wine'), ('4', 'cognac'), ('5', 'whiskey')], max_length=10)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='mainapp/img')),
                ('num_room', models.ManyToManyField(blank=True, related_name='num_room', to='mainapp.Room')),
            ],
        ),
    ]
