# Generated by Django 2.2 on 2019-05-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='type_of_drink',
            field=models.CharField(choices=[('non-alcoholic', 'non-alcoholic'), ('beer', 'beer'), ('wine', 'wine'), ('cognac', 'cognac'), ('whiskey', 'whiskey')], max_length=20),
        ),
    ]
