# Generated by Django 2.2 on 2019-05-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190526_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='visitors',
            field=models.ManyToManyField(blank=True, related_name='visitors', to='mainapp.Visitor'),
        ),
    ]
