# Generated by Django 2.2 on 2019-05-27 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_bar_visitors'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alcohole', models.CharField(max_length=20)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Visitor')),
            ],
        ),
    ]
